# Generated by Django 4.0.5 on 2022-06-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Record',
            fields=[
                ('Book_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Book_Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Author_Name', models.CharField(blank=True, default='Not available', max_length=30, null=True)),
                ('Catergory', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('Quantity', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='IssueBook_Record',
            fields=[
                ('Member_IdNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Member_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Book_Id', models.IntegerField(default='')),
                ('Book_Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Issuedate', models.DateTimeField(default='')),
                ('Expirydate', models.DateTimeField(default='')),
            ],
        ),
    ]
